version: '3.9'

volumes:
  mysql:

networks:
  svc: { }
  mysql: { }

services:
  system-mysql:
    image: "mysql:8.0.29"
    restart: on-failure
    hostname: mysql
    networks:
      - mysql
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_USER: "delivery"
      MYSQL_PASSWORD: "delivery"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "delivery"
    volumes:
      - mysql:/var/lib/mysql

  svc-delivery:
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        VERSION: "${VERSION}"
    restart: on-failure
    stdin_open: true
    tty: true
    image: "delivery:latest"
    networks:
      - svc
      - mysql
    ports:
      - "8443:443"
      - "8080:8080"
    environment:
      PORT: ":8080"

      ACCESS_SECRET: "access"
      REFRESH_SECRET: "refresh"

      ACCESS_LIFE_TIME: "10"
      REFRESH_LIFE_TIME: "60"

      DRIVER: "mysql"
      DATA_SOURCE_NAME: "delivery:delivery@tcp(mysql:3306)/delivery"
    depends_on:
      - system-mysql